version: '2.1'
services:
  aggregetion-service:
    build:
      context: .
    container_name: aggregetion-service
    image: aggregetionservice
    ports:
      - 8085:8085
    environment:
      EXTERNAL_SERVICE_HOST: host.docker.internal
    depends_on:
      - backend-services
  backend-services:
    container_name: backend-services
    image: qwkz/backend-services
    ports:
      - 4000:4000